name: google-cloud

on: [push]

jobs:

  build-gc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: _json_key
        password: "${{ secrets.GCLOUD_JSON_KEY }}"
        registry: gcr.io
        image_name: hello-world
